version: "3.8"
services:
  api:
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 150M
        reservations:
          cpus: "0.0001"
          memory: 20M
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: api-build
    #image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - ./images:/app/client/public/images
      - ./librechat.yaml:/app/librechat.yaml
  client:
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
        reservations:
          cpus: "0.0001"
          memory: 10M
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: prod-stage
    container_name: LibreChat-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf/:/var/www/certbot/:ro
  mongodb:
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 50M
        reservations:
          cpus: "0.0001"
          memory: 20M
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.0001"
          memory: 10M
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data:/meili_data
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
